# Generated by Django 5.2.6 on 2025-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Price List', max_length=200)),
                ('pdf_file', models.FileField(help_text='Upload price list PDF', upload_to='price_lists/')),
                ('version', models.CharField(help_text='Version number (e.g., v1.0, 2024-Q1)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of this price list')),
                ('is_active', models.BooleanField(default=True, help_text='Only one price list should be active')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['-upload_date'],
            },
        ),
    ]
