# Generated by Django 5.2.6 on 2025-09-09 09:07

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Short description for Page Preview'),
        ),
    ]
