# Generated by Django 5.2.6 on 2025-09-09 09:26

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_content_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', django_summernote.fields.SummernoteTextField()),
                ('content2', django_summernote.fields.SummernoteTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'ordering': ['-updated_at'],
            },
        ),
    ]
