# Generated by Django 5.2.6 on 2025-09-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content2',
            field=models.TextField(),
        ),
    ]
