# Generated by Django 5.2.6 on 2025-09-09 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aboutpage_content1_alter_aboutpage_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_meta_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content1',
            field=models.TextField(help_text='Main content section 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content2',
            field=models.TextField(help_text='Main content section 2'),
        ),
    ]
