# Generated by Django 5.2.6 on 2025-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1, help_text='Stock Keeping Unit - unique product identifier', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
