# Generated by Django 5.2.6 on 2025-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit - unique product identifier', max_length=100, unique=True),
        ),
    ]
