# Generated by Django 5.2.6 on 2025-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='seo_tags',
            field=models.CharField(blank=True, help_text='Comma-separated SEO tags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
