# Generated by Django 5.2.6 on 2025-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pricelist_seo_description_pricelist_seo_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_responded',
            field=models.BooleanField(default=False, help_text='Mark as True when enquiry has been responded to'),
        ),
    ]
