# Generated by Django 5.2.6 on 2025-09-14 18:15

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_enquiry_is_responded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature_Blocks',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='meta_description',
            new_name='seo_meta_description',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='tags',
            new_name='seo_meta_tags',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='seo_description',
            new_name='seo_meta_description',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='seo_tags',
            new_name='seo_meta_tags',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='seo_title',
            new_name='seo_meta_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seo_description',
            new_name='seo_meta_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seo_title',
            new_name='seo_meta_title',
        ),
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='is_responded',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='seo_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='seo_meta_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='seo_meta_tags',
            field=models.CharField(blank=True, help_text='Comma-separated SEO tags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_meta_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_tags',
            field=models.CharField(blank=True, help_text='Comma-separated SEO tags', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
