# Generated by Django 5.2.6 on 2025-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_feature_blocks_alter_page_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_meta_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_meta_description', models.TextField(blank=True, null=True)),
                ('seo_meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Pages',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
