# Generated by Django 5.2.6 on 2025-09-14 18:41

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_pageseo_delete_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageseo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='seo_meta_description',
        ),
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='seo_meta_name',
        ),
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='seo_meta_tags',
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='is_responded',
            field=models.BooleanField(default=False, help_text='Mark as True when contact has been responded to'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=1, help_text='Main page content'),
            preserve_default=False,
        ),
    ]
