# Generated by Django 5.2.6 on 2025-09-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_pageseo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='seo_meta_name',
            new_name='seo_meta_title',
        ),
        migrations.RenameField(
            model_name='pageseo',
            old_name='seo_meta_name',
            new_name='seo_meta_title',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='seo_meta_name',
            new_name='seo_meta_title',
        ),
    ]
