# Generated by Django 5.2.6 on 2025-09-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_seo_meta_name_aboutpage_seo_meta_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='seo_meta_tags',
            new_name='seo_meta_keywords',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='seo_meta_tags',
            new_name='seo_meta_keywords',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seo_meta_tags',
            new_name='seo_meta_keywords',
        ),
    ]
