# Generated by Django 5.2.6 on 2025-09-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_seo_meta_tags_blogpost_seo_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageseo',
            name='content',
        ),
    ]
