# Generated by Django 5.2.6 on 2025-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_pageseo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
