# Generated by Django 5.2.6 on 2025-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_pageseo_seo_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='seo_meta_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
