# Generated by Django 5.2.6 on 2025-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_pageseo_seo_meta_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
        migrations.AlterModelOptions(
            name='pageseo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Page SEO', 'verbose_name_plural': 'Pages SEO'},
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='seo_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
