# Generated by Django 5.2.6 on 2025-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_pagevisit_alter_pageseo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPostView',
        ),
    ]
