# Generated by Django 5.2.6 on 2025-09-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_pageseo_seo_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='seo_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
