# Generated by Django 5.2.6 on 2025-09-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_pageseo_seo_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='content1',
            field=models.TextField(default=1, help_text='Main content section 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageseo',
            name='content2',
            field=models.TextField(blank=True, help_text='Main content section 2', null=True),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='content3',
            field=models.TextField(blank=True, help_text='Main content section 3', null=True),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='content4',
            field=models.TextField(blank=True, help_text='Main content section 4', null=True),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='content5',
            field=models.TextField(blank=True, help_text='Main content section 5', null=True),
        ),
    ]
