# Generated by Django 5.2.6 on 2025-09-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_pageseo_content1_pageseo_content2_pageseo_content3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.AddField(
            model_name='productstatus',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
