# Generated by Django 5.2.6 on 2025-09-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_aboutpage_productstatus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='slug',
            field=models.SlugField(),
        ),
    ]
