# Generated by Django 5.2.6 on 2025-10-31 17:28

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_productstatus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
