"""
Django settings for starbliss project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "t")


if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'starblisspharma.co.in', 'www.starblisspharma.co.in']
else:
    ALLOWED_HOSTS = ['starblisspharma.co.in', 'www.starblisspharma.co.in']

CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://starblisspharma.co.in', 'https://www.starblisspharma.co.in']
SESSION_COOKIE_SECURE = True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # 

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'tailwind',
    'theme',  # Tailwind CSS app
    'django_summernote',
    'fontawesomefree',
    # 'whitenoise.runserver_nostatic',  # Keep WhiteNoise for static file serving
]


TAILWIND_APP_NAME = 'theme'

if DEBUG:
    NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
else:
    NPM_BIN_PATH = '/usr/bin/npm'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware'] 


ROOT_URLCONF = 'starbliss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'starbliss.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles-dir'
# Ensure the directory exists or comment out if not needed
STATICFILES_DIRS = [BASE_DIR / 'static']  # Remove or adjust if 'static' folder does not exist

# Media files (Uploaded images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# # Additional security settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    # SECURE_REFERRER_POLICY = "strict-origin"
    # SECURE_BROWSER_XSS_FILTER = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True





if DEBUG==True:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SUMMERNOTE_CONFIG = {
    "iframe": True,
    "summernote": {
        "airMode": False,
        "width": "100%",
        "height": 400,
        "codemirror": {
            "mode": "htmlmixed",
            "lineNumbers": True,
            "theme": "monokai"
        },
        "toolbar": [
            ["style", ["style"]],
            ["font", ["bold", "italic", "underline", "strikethrough", "clear"]],
            ["fontname", ["fontname"]],
            ["fontsize", ["fontsize"]],
            ["color", ["forecolor", "backcolor"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["height", ["height"]],
            ["table", ["table"]],
            ["insert", ["link", "picture", "video", "hr"]],
            ["view", ["fullscreen", "codeview", "help"]],
            ["misc", ["undo", "redo"]],
        ],
    },
    "css": (
        "/static/css/dist/styles.css",
        "/static/assets/css/pages/home.css",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    ),
    "css_for_inplace": (
        "/static/css/dist/styles.css",
    ),
    # "js": ("/static/css/","/static/assets/js/tailwind-config.js",
    #        ),
    "js_for_inplace": (),
    "disable_attachment": False,
    "attachment_require_authentication": True,
    "attachment_storage_class": None,
    "attachment_upload_to": "django-summernote/",
    "attachment_absolute_uri": False,
    "codemirror": {
        "mode": "htmlmixed",
        "lineNumbers": True,
        "theme": ""
    },
}

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "starbliss Pharmaceuticals",
    "SITE_HEADER": "starbliss Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/assets/images/logo.avif",  # path to your logo
        "dark": lambda request: "/static/assets/images/logo.avif",   # path to your logo
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/assets/images/logo.avif",  # path to your logo
        "dark": lambda request: "/static/assets/images/logo.avif",   # path to your logo
    },
    "SITE_SYMBOL": "A",  # symbol for the sidebar
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x16",
            "type": "image/png",
            "href": lambda request: "/static/assets/images/favicon.ico",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "starbliss.settings.environment_callback",
    # "DASHBOARD_CALLBACK": "starbliss.settings.dashboard_callback",  # Temporarily disabled
    "COLORS": {
        "primary": {
            "50": "239 68 68",  # red-500 - starbliss red theme
            "100": "220 38 38",
            "200": "185 28 28",
            "300": "153 27 27",
            "400": "127 29 29",
            "500": "239 68 68",  # Main red
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 10 10"
        },
        "secondary": {
            "50": "30 64 175",  # blue-800 - Secondary color
            "100": "29 78 216",
            "200": "37 99 235",
            "300": "59 130 246",
            "400": "96 165 250",
            "500": "147 197 253",
            "600": "191 219 254",
            "700": "219 234 254",
            "800": "239 246 255",
            "900": "59 130 246",
            "950": "30 64 175"
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "hi": "🇮🇳",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            # {
            #     "title": "Dashboard",
            #     "separator": True,
            #     "items": [
            #         {
            #             "title": "Analytics",
            #             "icon": "dashboard",
            #             "link": lambda request: "/admin/",
            #         },
            #     ],
            # },
            {
                "title": "Communications",
                "separator": True,
                "items": [
                    {
                        "title": "Enquiries",
                        "icon": "mail",
                        "link": lambda request: "/admin/app/enquiry/",
                    },
                    {
                        "title": "Contact Forms",
                        "icon": "contact_mail",
                        "link": lambda request: "/admin/app/contactformsubmission/",
                    },
                ],
            },
            {
                "title": "Product Management",
                "separator": True,
                "items": [
                    {
                        "title": "Product Categories",
                        "icon": "category",
                        "link": lambda request: "/admin/app/productcategory/",
                    },
                    {
                        "title": "Products",
                        "icon": "inventory",
                        "link": lambda request: "/admin/app/product/",
                    },
                    {
                        "title": "Product Status",
                        "icon": "assignment_turned_in",
                        "link": lambda request: "/admin/app/productstatus/",
                    },
                    {
                        "title": "Price List",
                        "icon": "list_alt",
                        "link": lambda request: "/admin/app/pricelist/",
                    },
                ],
            },
            {
                "title": "Content Management",
                "separator": True,
                "items": [
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": lambda request: "/admin/app/blogpost/",
                    },
                    {
                        "title": "Blog Categories",
                        "icon": "bookmark",
                        "link": lambda request: "/admin/app/blogcategory/",
                    },
                    {
                        "title": "SEO Pages",
                        "icon": "description",
                        "link": lambda request: "/admin/app/pageseo/",
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": lambda request: "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "app.product",
                "app.productcategory", 
                "app.productstatus",
                "app.pricelist",
            ],
            "items": [
                {
                    "title": "Product Categories",
                    "link": lambda request: "/admin/app/productcategory/",
                },
                {
                    "title": "Products", 
                    "link": lambda request: "/admin/app/product/",
                },
                {
                    "title": "Product Status",
                    "link": lambda request: "/admin/app/productstatus/",
                },
                {
                    "title": "Price Lists",
                    "link": lambda request: "/admin/app/pricelist/",
                },
            ],
        },
        {
            "models": [
                "app.blogpost",
                "app.blogcategory",
                "app.pageseo",
            ],
            "items": [
                {
                    "title": "Blog Posts",
                    "link": lambda request: "/admin/app/blogpost/",
                },
                {
                    "title": "Blog Categories",
                    "link": lambda request: "/admin/app/blogcategory/",
                },
                {
                    "title": "SEO Pages",
                    "link": lambda request: "/admin/app/pageseo/",
                },
            ],
        },
        {
            "models": [
                "app.enquiry",
                "app.contactformsubmission",
            ],
            "items": [
                {
                    "title": "Enquiries",
                    "link": lambda request: "/admin/app/enquiry/",
                },
                {
                    "title": "Contact Forms",
                    "link": lambda request: "/admin/app/contactformsubmission/",
                },
            ],
        },
    ],
}

def environment_callback(request):
    """Callback to show environment in admin header"""
    # if not DEBUG:
    #     return ["Production", "success"]
    return ["Production", "success"]  # [label, color]

